# Versiones
nginx_version: "1.24"
wordpress_version: "6.5.3"
mysql_version: "8.0"

# Configuraci√≥n de base de datos
mysql_root_password: rootpass

mysql_databases:
  - name: wordpress
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: wpuser
    host: localhost
    password: secret123
    priv: "wordpress.*:ALL"
